leftnav:
- identifier: 8d16c9b4-f619-178e-1fcb-c5a554ec740a
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 86c11d7c-0d2f-ba99-e47b-8d61cf12f546
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: d6b2bc76-9727-8893-00de-7f1761a7a830
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 542b7b54-b44b-165e-dbe0-50fcd49e3e10
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 40
- identifier: 1be07034-a38c-84cf-48f2-51d69ffc0a28
  name: Assignments
  url: /pages/assignments
  weight: 50
- identifier: f8649f62-6baf-b12d-a50c-2a55e351faa7
  name: Exams
  url: /pages/exams
  weight: 60
